# Generated by Django 5.2.12 on 2026-04-02 10:44

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProfilInvestisseur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enveloppe",
                    models.CharField(
                        choices=[
                            ("pea", "PEA classique"),
                            ("pea_pme", "PEA-PME"),
                            ("cto", "Compte-titres ordinaire"),
                        ],
                        default="pea",
                        max_length=10,
                    ),
                ),
                (
                    "plafond_versements",
                    models.DecimalField(
                        decimal_places=2, default=150000.0, max_digits=10
                    ),
                ),
                (
                    "versements_effectues",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("date_ouverture", models.DateField(blank=True, null=True)),
                ("horizon_min_ans", models.PositiveSmallIntegerField(default=7)),
                ("horizon_max_ans", models.PositiveSmallIntegerField(default=15)),
                (
                    "style",
                    models.CharField(
                        choices=[
                            ("croissance", "Croissance"),
                            ("valeur", "Valeur"),
                            ("dividendes", "Dividendes"),
                            ("mixte", "Mixte"),
                        ],
                        default="croissance",
                        max_length=15,
                    ),
                ),
                (
                    "tolerance_risque",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Prudente"),
                            (2, "Modérée-faible"),
                            (3, "Modérée"),
                            (4, "Modérée-élevée"),
                            (5, "Dynamique"),
                        ],
                        default=3,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "poids_fondamentaux",
                    models.PositiveSmallIntegerField(
                        default=60,
                        help_text="% du score de confluence attribué aux fondamentaux",
                    ),
                ),
                (
                    "poids_technique",
                    models.PositiveSmallIntegerField(
                        default=40,
                        help_text="% du score de confluence attribué à l'analyse technique",
                    ),
                ),
                (
                    "ignorer_signaux_court_terme",
                    models.BooleanField(
                        default=True, help_text="Ignorer signaux < 1 semaine"
                    ),
                ),
                (
                    "mode_accumulation",
                    models.BooleanField(
                        default=True,
                        help_text="Alertes de renforcement uniquement — pas de suggestions de vente",
                    ),
                ),
                (
                    "seuil_drawdown_alerte",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Alerte si baisse > X% pour réévaluer la thèse",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "digest_hebdomadaire",
                    models.BooleanField(
                        default=True, help_text="Résumé hebdomadaire le vendredi soir"
                    ),
                ),
                (
                    "pays_eligibles_pea",
                    models.JSONField(
                        default=list,
                        help_text="Codes ISO-3 des pays dont les actions sont éligibles PEA",
                    ),
                ),
                ("date_maj", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Profil investisseur",
            },
        ),
        migrations.CreateModel(
            name="ApiQuota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "api",
                    models.CharField(help_text="eodhd | fmp | newsapi", max_length=20),
                ),
                ("date", models.DateField()),
                ("nb_requetes", models.PositiveSmallIntegerField(default=0)),
                ("date_maj", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("api", "date")},
            },
        ),
        migrations.CreateModel(
            name="Titre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ticker",
                    models.CharField(
                        help_text="Ticker (MC.PA), ISIN (FR0010557264) ou nom (AB Science)",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("isin", models.CharField(blank=True, max_length=12)),
                (
                    "nom",
                    models.CharField(
                        blank=True,
                        help_text="Auto-rempli via EODHD si vide",
                        max_length=120,
                    ),
                ),
                (
                    "nom_court",
                    models.CharField(
                        blank=True, help_text="Ex: LVMH, Air Liquide", max_length=20
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        blank=True, help_text="Ex: EPA, AMS, XETRA", max_length=20
                    ),
                ),
                (
                    "pays",
                    models.CharField(
                        blank=True,
                        help_text="Code ISO-3 : FRA, DEU, NLD… (auto-rempli)",
                        max_length=3,
                    ),
                ),
                ("secteur", models.CharField(blank=True, max_length=80)),
                ("sous_secteur", models.CharField(blank=True, max_length=80)),
                ("eligible_pea", models.BooleanField(default=False)),
                ("date_verif_eligibilite", models.DateField(blank=True, null=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("portefeuille", "En portefeuille"),
                            ("surveillance", "En surveillance"),
                            ("archive", "Archivé"),
                        ],
                        default="surveillance",
                        max_length=20,
                    ),
                ),
                (
                    "lot",
                    models.CharField(
                        choices=[
                            ("A", "Lot A — lundi/mercredi"),
                            ("B", "Lot B — mardi/jeudi"),
                        ],
                        default="A",
                        help_text="Lot de rotation pour les appels API fondamentaux",
                        max_length=1,
                    ),
                ),
                ("nb_actions", models.PositiveIntegerField(default=0)),
                (
                    "prix_revient_moyen",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                ("date_premier_achat", models.DateField(blank=True, null=True)),
                (
                    "score_conviction",
                    models.IntegerField(
                        blank=True,
                        help_text="Score 0-100 combinant technique+fondamentaux+sentiment+historique",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "explication_conviction",
                    models.TextField(
                        blank=True,
                        help_text="Explication IA 2-3 phrases du score de conviction",
                    ),
                ),
                ("date_calcul_conviction", models.DateTimeField(blank=True, null=True)),
                ("actif", models.BooleanField(default=True)),
                ("date_ajout", models.DateTimeField(auto_now_add=True)),
                ("date_maj", models.DateTimeField(auto_now=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Titre",
                "ordering": ["nom"],
                "indexes": [
                    models.Index(fields=["statut"], name="app_titre_statut_c6aa91_idx"),
                    models.Index(fields=["lot"], name="app_titre_lot_8a2df6_idx"),
                    models.Index(
                        fields=["eligible_pea"], name="app_titre_eligibl_95831a_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Signal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "type_signal",
                    models.CharField(
                        choices=[
                            ("rsi_survente", "RSI zone survente (<40)"),
                            ("rsi_surachat", "RSI zone surachat (>65)"),
                            ("macd_haussier", "MACD croisement haussier"),
                            ("macd_baissier", "MACD croisement baissier"),
                            ("mm_golden_cross", "Golden cross MM20/MM50"),
                            ("mm_death_cross", "Death cross MM20/MM50"),
                            ("boll_inf", "Prix proche bande Bollinger basse"),
                            ("boll_sup", "Prix proche bande Bollinger haute"),
                            ("volume_spike", "Pic de volume anormal"),
                            ("sentiment_hausse", "Sentiment en forte hausse"),
                            ("sentiment_baisse", "Sentiment en forte baisse"),
                            ("fondamental", "Signal fondamental"),
                            ("renforcement", "Opportunité de renforcement"),
                            ("pattern_graphique", "Pattern graphique détecté"),
                            ("sectorielle", "Alerte sectorielle"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("haussier", "Haussier"),
                            ("baissier", "Baissier"),
                            ("neutre", "Neutre"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "valeur",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Valeur de l'indicateur au moment du signal",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=200)),
                (
                    "actif",
                    models.BooleanField(
                        default=True, help_text="False une fois intégré dans une alerte"
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "titre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signaux",
                        to="app.titre",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "titre"],
            },
        ),
        migrations.CreateModel(
            name="ScoreSentiment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("presse", "Presse financière"),
                            ("social", "Réseaux sociaux"),
                            ("global", "Score global pondéré"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("-1.000")),
                            django.core.validators.MaxValueValidator(Decimal("1.000")),
                        ],
                    ),
                ),
                ("nb_articles", models.PositiveSmallIntegerField(default=0)),
                (
                    "score_min",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=4, null=True
                    ),
                ),
                (
                    "score_max",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=4, null=True
                    ),
                ),
                (
                    "variation_24h",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Variation du score vs j-1",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "resume_ia",
                    models.TextField(
                        blank=True, help_text="Résumé IA des thèmes principaux détectés"
                    ),
                ),
                ("date_calcul", models.DateTimeField(auto_now_add=True)),
                (
                    "titre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores_sentiment",
                        to="app.titre",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="PrixJournalier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("ouverture", models.DecimalField(decimal_places=4, max_digits=12)),
                ("haut", models.DecimalField(decimal_places=4, max_digits=12)),
                ("bas", models.DecimalField(decimal_places=4, max_digits=12)),
                ("cloture", models.DecimalField(decimal_places=4, max_digits=12)),
                (
                    "cloture_veille",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Clôture J-1 pour calcul variation vs veille",
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("volume", models.BigIntegerField(default=0)),
                (
                    "rsi_14",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "macd",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "macd_signal",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "macd_hist",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "mm_20",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "mm_50",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "mm_200",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "boll_sup",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "boll_mid",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "boll_inf",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "volume_ratio",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Volume / moyenne volume 20j",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "date_calcul_indicateurs",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "titre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prix_journaliers",
                        to="app.titre",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="PatternDetecte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_pattern",
                    models.CharField(
                        choices=[
                            ("double_bottom", "Double creux"),
                            ("double_top", "Double sommet"),
                            ("head_shoulders", "Tête-épaules"),
                            ("inv_head_shoulders", "Tête-épaules inversée"),
                            ("triangle_asc", "Triangle ascendant"),
                            ("triangle_desc", "Triangle descendant"),
                            ("triangle_sym", "Triangle symétrique"),
                            ("channel_asc", "Canal ascendant"),
                            ("channel_desc", "Canal descendant"),
                            ("flag", "Drapeau"),
                            ("pennant", "Fanion"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_formation", "En formation"),
                            ("confirme", "Confirmé"),
                            ("invalide", "Invalidé"),
                        ],
                        default="en_formation",
                        max_length=15,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("haussier", "Haussier"),
                            ("baissier", "Baissier"),
                            ("neutre", "Neutre"),
                        ],
                        max_length=10,
                    ),
                ),
                ("date_debut", models.DateField()),
                (
                    "date_fin",
                    models.DateField(
                        blank=True,
                        help_text="Null = pattern encore en formation",
                        null=True,
                    ),
                ),
                ("date_detection", models.DateTimeField(auto_now_add=True)),
                (
                    "prix_support",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "prix_resistance",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "prix_objectif",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Objectif basé sur la hauteur du pattern",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "prix_invalidation",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "points_cles",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="[{time, value, label}] pour les marqueurs chart",
                    ),
                ),
                (
                    "fiabilite",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Fiabilité historique %",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description en langage débutant"
                    ),
                ),
                (
                    "titre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patterns",
                        to="app.titre",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_detection"],
            },
        ),
        migrations.CreateModel(
            name="Fondamentaux",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_maj", models.DateField()),
                (
                    "per",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Price/Earnings Ratio",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "per_forward",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "peg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "p_book",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "ev_ebitda",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "capitalisation",
                    models.BigIntegerField(blank=True, help_text="En euros", null=True),
                ),
                (
                    "roe",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Return on Equity %",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "roa",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "marge_nette",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="%",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "marge_operationnelle",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="%",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "dette_nette_ebitda",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Ratio dette nette / EBITDA",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "couverture_interets",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "cash_flow_libre",
                    models.BigIntegerField(
                        blank=True, help_text="FCF en euros", null=True
                    ),
                ),
                (
                    "croissance_bpa_1an",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="%",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "croissance_bpa_3ans",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="% annualisé",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "croissance_ca_1an",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="%",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "rendement_dividende",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="%",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "dividende_par_action",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=8, null=True
                    ),
                ),
                (
                    "payout_ratio",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="%",
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("date_ex_dividende", models.DateField(blank=True, null=True)),
                ("date_paiement", models.DateField(blank=True, null=True)),
                (
                    "objectif_cours_moyen",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "nb_analystes",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "consensus",
                    models.CharField(
                        blank=True, help_text="Buy / Hold / Sell", max_length=20
                    ),
                ),
                (
                    "analyse_ia",
                    models.TextField(
                        blank=True,
                        help_text="Analyse qualitative IA : forces, faiblesses, positionnement sectoriel",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        default="eodhd", help_text="eodhd | fmp | manuel", max_length=20
                    ),
                ),
                (
                    "titre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fondamentaux",
                        to="app.titre",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_maj"],
                "get_latest_by": "date_maj",
            },
        ),
        migrations.CreateModel(
            name="DocumentTitre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fichier", models.FileField(upload_to="documents/%Y/%m/")),
                (
                    "nom",
                    models.CharField(
                        help_text="Nom affiché du document", max_length=200
                    ),
                ),
                (
                    "type_doc",
                    models.CharField(
                        choices=[
                            ("rapport_annuel", "Rapport annuel"),
                            ("etude_clinique", "Étude clinique"),
                            ("news", "Article / News"),
                            ("analyse", "Analyse / Note"),
                            ("autre", "Autre"),
                        ],
                        default="autre",
                        max_length=20,
                    ),
                ),
                (
                    "taille",
                    models.PositiveIntegerField(
                        default=0, help_text="Taille en octets"
                    ),
                ),
                (
                    "texte_extrait",
                    models.TextField(
                        blank=True, help_text="Contenu textuel extrait pour l'IA"
                    ),
                ),
                (
                    "resume_ia",
                    models.TextField(
                        blank=True, help_text="Résumé IA du document (3-5 phrases)"
                    ),
                ),
                ("date_upload", models.DateTimeField(auto_now_add=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Commentaire libre de l'utilisateur"
                    ),
                ),
                (
                    "titre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="app.titre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Document",
                "ordering": ["-date_upload"],
            },
        ),
        migrations.CreateModel(
            name="ArticleSectoriel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("secteur", models.CharField(max_length=80)),
                ("date_pub", models.DateTimeField()),
                ("source", models.CharField(default="google_news", max_length=20)),
                ("url", models.URLField(blank=True, max_length=500)),
                ("titre_art", models.CharField(max_length=300)),
                ("extrait", models.TextField(blank=True)),
                (
                    "impact_secteur",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Score impact -1 à +1",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "type_impact",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("regulation", "Régulation"),
                            ("concurrence", "Concurrence"),
                            ("macro", "Événement macro"),
                            ("resultats_secteur", "Résultats sectoriels"),
                            ("innovation", "Innovation"),
                            ("restructuration", "Restructuration"),
                            ("autre", "Autre"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "analyse_ia",
                    models.TextField(
                        blank=True, help_text="Explication LLM de l'impact sectoriel"
                    ),
                ),
                ("date_collecte", models.DateTimeField(auto_now_add=True)),
                (
                    "titres_impactes",
                    models.ManyToManyField(
                        blank=True, related_name="articles_sectoriels", to="app.titre"
                    ),
                ),
            ],
            options={
                "ordering": ["-date_pub"],
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_pub", models.DateTimeField()),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("newsapi", "NewsAPI"),
                            ("eodhd", "EODHD News"),
                            ("google_news", "Google News"),
                            ("boursorama", "Boursorama"),
                            ("zonebourse", "Zonebourse"),
                            ("reddit", "Reddit"),
                            ("stocktwits", "StockTwits"),
                        ],
                        max_length=20,
                    ),
                ),
                ("url", models.URLField(blank=True, max_length=500)),
                ("titre_art", models.CharField(max_length=300)),
                ("extrait", models.TextField(blank=True)),
                ("auteur", models.CharField(blank=True, max_length=100)),
                (
                    "score_sentiment",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=4,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("-1.000")),
                            django.core.validators.MaxValueValidator(Decimal("1.000")),
                        ],
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Topics détectés : résultats, fusion, dividende…",
                    ),
                ),
                ("date_scoring", models.DateTimeField(blank=True, null=True)),
                ("date_collecte", models.DateTimeField(auto_now_add=True)),
                (
                    "titre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="articles",
                        to="app.titre",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_pub"],
            },
        ),
        migrations.CreateModel(
            name="AlerteConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("actif", models.BooleanField(default=True)),
                (
                    "score_min_declenchement",
                    models.DecimalField(
                        decimal_places=1,
                        default=5.0,
                        help_text="Score de confluence minimum pour déclencher une alerte (0-10)",
                        max_digits=3,
                    ),
                ),
                ("notif_app", models.BooleanField(default=True)),
                ("notif_email", models.BooleanField(default=False)),
                ("notif_telegram", models.BooleanField(default=False)),
                ("notif_webhook", models.BooleanField(default=False)),
                ("webhook_url", models.URLField(blank=True)),
                (
                    "ignorer_court_terme",
                    models.BooleanField(
                        default=True, help_text="Ignorer signaux < 1 semaine"
                    ),
                ),
                (
                    "alertes_renforcement",
                    models.BooleanField(
                        default=True,
                        help_text="Signaux d'entrée uniquement (profil PEA)",
                    ),
                ),
                (
                    "seuil_drawdown",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Alerte si baisse > X% depuis le plus haut récent",
                        max_digits=4,
                        null=True,
                    ),
                ),
                ("date_maj", models.DateTimeField(auto_now=True)),
                (
                    "titre",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerte_config",
                        to="app.titre",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Alerte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_detection", models.DateTimeField(auto_now_add=True)),
                (
                    "date_signal",
                    models.DateField(
                        help_text="Date des données ayant déclenché l'alerte"
                    ),
                ),
                (
                    "score_confluence",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("10")),
                        ],
                    ),
                ),
                (
                    "niveau",
                    models.CharField(
                        choices=[
                            ("forte", "Forte (score 8-10)"),
                            ("moderee", "Modérée (score 5-7)"),
                            ("surveillance", "Surveillance (score 3-4)"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "cours_au_signal",
                    models.DecimalField(decimal_places=4, max_digits=12),
                ),
                (
                    "rsi_au_signal",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "sentiment_au_signal",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=4, null=True
                    ),
                ),
                (
                    "texte_ia",
                    models.TextField(help_text="Observation rédigée par le LLM"),
                ),
                (
                    "fiabilite_historique",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="% de fois où ce pattern a été suivi d'une hausse sur ce titre",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "nb_occurrences_passees",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Nombre de fois où ce pattern s'est présenté sur ce titre",
                        null=True,
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("nouvelle", "Nouvelle"),
                            ("vue", "Vue"),
                            ("archivee", "Archivée"),
                        ],
                        default="nouvelle",
                        max_length=15,
                    ),
                ),
                ("note_utilisateur", models.TextField(blank=True)),
                (
                    "signaux",
                    models.ManyToManyField(
                        blank=True, related_name="alertes", to="app.signal"
                    ),
                ),
                (
                    "titre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alertes",
                        to="app.titre",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_detection"],
            },
        ),
        migrations.AddIndex(
            model_name="signal",
            index=models.Index(
                fields=["titre", "date"], name="app_signal_titre_i_aa5eec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="signal",
            index=models.Index(
                fields=["actif", "date"], name="app_signal_actif_e19934_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scoresentiment",
            index=models.Index(
                fields=["titre", "date"], name="app_scorese_titre_i_f234cc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scoresentiment",
            index=models.Index(
                fields=["date", "source"], name="app_scorese_date_9584a1_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="scoresentiment",
            unique_together={("titre", "date", "source")},
        ),
        migrations.AddIndex(
            model_name="prixjournalier",
            index=models.Index(
                fields=["titre", "date"], name="app_prixjou_titre_i_8bb00c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="prixjournalier",
            index=models.Index(fields=["date"], name="app_prixjou_date_3ef6c4_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="prixjournalier",
            unique_together={("titre", "date")},
        ),
        migrations.AddIndex(
            model_name="patterndetecte",
            index=models.Index(
                fields=["titre", "date_detection"],
                name="app_pattern_titre_i_c00ad0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="patterndetecte",
            index=models.Index(fields=["statut"], name="app_pattern_statut_c55194_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="fondamentaux",
            unique_together={("titre", "date_maj")},
        ),
        migrations.AddIndex(
            model_name="articlesectoriel",
            index=models.Index(
                fields=["secteur", "date_pub"], name="app_article_secteur_ed19c4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["titre", "date_pub"], name="app_article_titre_i_3da167_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["source", "date_pub"], name="app_article_source_059772_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alerte",
            index=models.Index(
                fields=["titre", "date_detection"], name="app_alerte_titre_i_b35dc1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alerte",
            index=models.Index(fields=["statut"], name="app_alerte_statut_dcbdf8_idx"),
        ),
        migrations.AddIndex(
            model_name="alerte",
            index=models.Index(fields=["niveau"], name="app_alerte_niveau_09a68e_idx"),
        ),
    ]
